import { Language } from './translations';

export const uiCopy: Record<Language, Record<string, string>> = {
  en: {
    findDoctors: 'Find Doctors',
    welcomeToPsyNova: 'Welcome To PsyNova',
    heroHeadlinePrefix: 'The',
    heroHeadlineHighlight: 'Healthy',
    heroHeadlineSuffix: 'Mind Is A Wealthy Soul',
    highStress: 'High stress',
    calmingShoreline: 'Calming shoreline',
    shorelineMeta: 'Sri Lanka Calming Shoreline Metaphor',
    shorelineResult: 'Transitioning anxiety into absolute peace',
    getStarted: "Let's Get Started",
    watchIntro: 'Watch Intro Video',
    founderTitle: 'Chief Psychiatrist / Founder',
    happySouls: '1000+ Happy Souls',
    activePatientBase: 'Active Patient Base',
    yearsExperience: 'Years Experience',
    activeMembers: 'Active Members',
    satisfiedClient: 'Satisfied Client',
    trustedPatients: 'Trusted By 100,245+ PsyNova Patients Across Sri Lanka',
    aboutUs: 'About Us',
    ourVision: 'Our Vision',
    ourVisionText: 'Pioneering state-of-the-art mental care accessibility for every home across Sri Lanka.',
    ourMission: 'Our Mission',
    ourMissionText: 'Delivering empathetic, fully certified and secure tele-health treatments instantly.',
    qualityCarePrefix: 'Quality Care From Quality',
    qualityCareHighlight: 'Experts',
    aboutPreviewText: "At PsyNova, we gather Sri Lanka's leading licensed psychiatrists to assist you through virtual consultation sessions. From diagnostic checkups to treatment programs, our platform guarantees highly certified, discrete and supportive clinical results without high hospital costs or travel constraints.",
    learnMore: 'Learn More',
    whyChooseUs: 'Why Choose Us',
    gettingYouPrefix: 'Getting You',
    gettingYouHighlight: 'Back',
    gettingYouSuffix: 'In Shape',
    whyChooseText: 'Empathetic clinical consultations tailored perfectly around your personal timeline, language requirements and local privacy needs.',
    personalizedCare: 'Personalized Care',
    personalizedCareText: 'Custom clinical reports, medicine instructions and diagnostic reviews created by leading medical specialists.',
    sandboxTools: 'Free Sandbox Tools',
    sandboxToolsText: 'Explore simulated billing checkouts, view mock SMS dispatches, and trigger instant tele-health rooms.',
    goodService: '24/7 Good Service',
    goodServiceText: 'Our Sri Lankan compliance desk is online to assist with scheduling, refund requests and administrative security audits.',
    searchSub: 'Search and secure live sessions instantly below',
    filtersClear: 'Filters Clear',
    noSlots: 'No active slots published.',
    noDoctors: 'No psychiatrists match your search filter criteria.',
    slmcOk: 'SLMC OK',
    slmcPendingShort: 'SLMC PENDING',
    footerAbout: 'Connecting clients with verified SLMC-licensed expert psychiatrists. 100% online, secure, and multi-lingual.',
    quickNav: 'Quick Navigations',
    legal: 'Legal',
    pdpaCompliance: 'PDPA Compliance',
    pdpaText: 'Fully compliant with the Sri Lanka Personal Data Protection Act (PDPA) No. 9 of 2022. All clinical recordings are strictly barred.',
    footerCopyright: '© 2026 PsyNova. Developed and optimized for the Ministry of Health tele-psychiatry standard.',
    cancel: 'Cancel',
    close: 'Close',
    specialist: 'Specialist',
    dateAndTime: 'Date & Time',
    doctorFee: 'Doctor Consultation Fee',
    platformCommission: 'Platform Service commission',
    cardNumber: 'Card Number',
    cardHint: 'Enter 12 digits for success, less to fail',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    lankaPayRouting: 'LankaPay Dynamic Routing',
    lankaPayText: 'Your payment request will be routed dynamically through LankaPay national switch instantly. Safe, local, and direct.',
    authorizing: 'Authorizing transaction via secure network...',
    payhereGateway: 'PayHere Gateway',
    patientRegistration: 'Patient Registration',
    patientRegistrationTitle: 'Create Patient Account',
    patientRegistrationSub: 'You must verify your identity to reserve a psychiatric appointment.',
    quickSandboxAccess: 'Quick Sandbox Account Access',
    quickSandboxText: "Immediately logs in as client 'Kavindu' to skip forms.",
    useKavindu: 'Use Kavindu',
    fullName: 'Full Name',
    nicPassport: 'NIC / Passport Number',
    mobilePhone: 'Mobile Phone',
    email: 'Email',
    district: 'District',
    password: 'Password',
    registerProceed: 'Register & Proceed To Checkout',
    jitsiRoom: 'Jitsi Meet Live Room',
    exitRoom: 'Exit Room',
    activeConsultationRoom: 'Active Consultation Room',
    consultation: 'Consultation',
    telehealthLink: 'Tele-health Session Link (Jitsi Meet)',
    closeSessionSubmit: 'Close Session & Submit Clinical Record',
    fileIncident: 'File Incident',
    complaintReviewText: 'Your grievance will be reviewed manually by PsyNova compliance officers.',
    complaintSuccess: 'Complaint filed successfully! Check the SMS logs below to see confirmation dispatch.',
    bookingAssociated: 'Booking Associated',
    appointmentWith: 'Appointment',
    provideDetails: 'Provide precise details here...',
    submitTicket: 'Submit Ticket to Compliance Office',
    accountType: 'Account Type',
    clientLoginHint: 'Mobile number + password client login',
    invalidLogin: 'Invalid mobile/password or suspended account.',
    mobileNumber: 'Mobile Number',
    timeLeft: 'Time left',
    profileNotFound: 'Profile not found',
    backToSearch: 'Back to search',
    backToSpecialists: 'Back to specialists',
    paymentExpired: 'Payment window expired. The appointment slot has been released.',
    switchToClient: 'Please switch role to Client to book an appointment!',
    slotPublished: 'Slot published successfully!',
    doctorRegistrationSubmitted: 'Registration submitted! Undergoing mandatory SLMC verification by PsyNova Admins.',
  },
  si: {
    findDoctors: 'වෛද්‍යවරුන් සොයන්න',
    welcomeToPsyNova: 'PsyNova වෙත සාදරයෙන් පිළිගනිමු',
    heroHeadlinePrefix: 'සුව',
    heroHeadlineHighlight: 'මනසක්',
    heroHeadlineSuffix: 'සාර්ථක ජීවිතයක පදනමයි',
    highStress: 'ඉහළ ආතතිය',
    calmingShoreline: 'සන්සුන් වෙරළ',
    shorelineMeta: 'ශ්‍රී ලංකා සන්සුන් වෙරළ උපමාව',
    shorelineResult: 'කාංසාව සන්සුන් බවකට පරිවර්තනය කිරීම',
    getStarted: 'ආරම්භ කරන්න',
    watchIntro: 'හැඳින්වීම බලන්න',
    founderTitle: 'ප්‍රධාන මනෝ වෛද්‍ය / ආරම්භක',
    happySouls: '1000+ සතුටු සේවාලාභීන්',
    activePatientBase: 'සක්‍රීය රෝගී පදනම',
    yearsExperience: 'වසරක පළපුරුද්ද',
    activeMembers: 'සක්‍රීය සාමාජිකයන්',
    satisfiedClient: 'සතුටු සේවාලාභීන්',
    trustedPatients: 'ශ්‍රී ලංකාව පුරා PsyNova සේවාලාභීන් 100,245+ ක විශ්වාසය',
    aboutUs: 'අප ගැන',
    ourVision: 'අපගේ දැක්ම',
    ourVisionText: 'ශ්‍රී ලංකාවේ සෑම නිවසකටම නවීන මානසික සෞඛ්‍ය සේවාව පහසුවෙන් ලබාදීම.',
    ourMission: 'අපගේ මෙහෙවර',
    ourMissionText: 'සහතිකලත්, ආරක්ෂිත සහ කරුණාවන්ත මාර්ගගත සෞඛ්‍ය සේවාවක් කඩිනමින් ලබාදීම.',
    qualityCarePrefix: 'ගුණාත්මක සේවාව',
    qualityCareHighlight: 'විශේෂඥයින්ගෙන්',
    aboutPreviewText: 'PsyNova තුළින් ශ්‍රී ලංකාවේ ලියාපදිංචි විශේෂඥ මනෝ වෛද්‍යවරුන් සමඟ මාර්ගගතව සම්බන්ධ විය හැක. රෝහල් ගමන් වියදම් හෝ අනවශ්‍ය ප්‍රමාදයන් නොමැතිව ආරක්ෂිත උපදේශන ලබාගැනීමට අපි පහසුකම් සපයන්නෙමු.',
    learnMore: 'තව දැනගන්න',
    whyChooseUs: 'අප තෝරාගත යුත්තේ ඇයි',
    gettingYouPrefix: 'ඔබව නැවත',
    gettingYouHighlight: 'සුවතාවයට',
    gettingYouSuffix: 'ගෙන යාම',
    whyChooseText: 'ඔබේ කාලසටහන, භාෂාව සහ පෞද්ගලිකත්ව අවශ්‍යතා අනුව සකස් කළ කරුණාවන්ත සායනික උපදේශන.',
    personalizedCare: 'පුද්ගලික කළ සත්කාර',
    personalizedCareText: 'විශේෂඥ වෛද්‍යවරුන් විසින් සකස් කරන වාර්තා, ඖෂධ උපදෙස් සහ සායනික සමාලෝචන.',
    sandboxTools: 'නොමිලේ පරීක්ෂණ මෙවලම්',
    sandboxToolsText: 'ගෙවීම් පරීක්ෂණ, SMS ලොග් සහ වීඩියෝ කාමර පරීක්ෂා කිරීමේ පහසුකම්.',
    goodService: '24/7 හොඳ සේවාව',
    goodServiceText: 'වෙන්කිරීම්, මුදල් ආපසු ගෙවීම් සහ ආරක්ෂක විමසුම් සඳහා දේශීය සහාය කණ්ඩායම.',
    searchSub: 'සජීවී සැසි සෙවීමට සහ වෙන්කරවා ගැනීමට පහත භාවිතා කරන්න',
    filtersClear: 'පෙරහන් ඉවත් කරන්න',
    noSlots: 'සක්‍රීය වේලාවන් නොමැත.',
    noDoctors: 'ඔබගේ පෙරහන් වලට ගැළපෙන මනෝ වෛද්‍යවරුන් නොමැත.',
    slmcOk: 'SLMC අනුමතයි',
    slmcPendingShort: 'SLMC අපේක්ෂිතයි',
    footerAbout: 'SLMC ලියාපදිංචි විශේෂඥ මනෝ වෛද්‍යවරුන් සමඟ සේවාලාභීන් සම්බන්ධ කරන 100% මාර්ගගත, ආරක්ෂිත, බහුභාෂා වේදිකාවක්.',
    quickNav: 'ඉක්මන් සබැඳි',
    legal: 'නීතිමය',
    pdpaCompliance: 'PDPA අනුකූලතාව',
    pdpaText: 'ශ්‍රී ලංකා පෞද්ගලික දත්ත ආරක්ෂණ පනතට අනුකූලයි. සායනික රෙකෝඩ් කිරීම සම්පූර්ණයෙන් තහනම්ය.',
    footerCopyright: '© 2026 PsyNova. ශ්‍රී ලංකා tele-psychiatry ප්‍රමිතිය සඳහා සංවර්ධනය කරන ලදී.',
    cancel: 'අවලංගු කරන්න',
    close: 'වසන්න',
    specialist: 'විශේෂඥයා',
    dateAndTime: 'දිනය සහ වේලාව',
    doctorFee: 'වෛද්‍ය උපදේශන ගාස්තුව',
    platformCommission: 'වේදිකා සේවා ගාස්තුව',
    cardNumber: 'කාඩ් අංකය',
    cardHint: 'සාර්ථක පරීක්ෂාවට අංක 12ක් ඇතුළත් කරන්න',
    expiryDate: 'කල් ඉකුත් දිනය',
    cvv: 'CVV',
    lankaPayRouting: 'LankaPay මාර්ගගත කිරීම',
    lankaPayText: 'ඔබගේ ගෙවීම් ඉල්ලීම LankaPay ජාතික පද්ධතිය හරහා ආරක්ෂිතව යොමු කෙරේ.',
    authorizing: 'ආරක්ෂිත ජාලය හරහා ගෙවීම අනුමත කරමින්...',
    payhereGateway: 'PayHere ද්වාරය',
    patientRegistration: 'රෝගී ලියාපදිංචිය',
    patientRegistrationTitle: 'සේවාලාභී ගිණුම සාදන්න',
    patientRegistrationSub: 'මානසික වෛද්‍ය සැසියක් වෙන්කරවා ගැනීමට ඔබේ අනන්‍යතාව තහවුරු කළ යුතුය.',
    quickSandboxAccess: 'ඉක්මන් පරීක්ෂණ ගිණුම',
    quickSandboxText: 'පෝරම මඟහැර Kavindu සේවාලාභී ගිණුමෙන් ඇතුල් වේ.',
    useKavindu: 'Kavindu භාවිතා කරන්න',
    fullName: 'සම්පූර්ණ නම',
    nicPassport: 'NIC / විදේශ ගමන් බලපත්‍ර අංකය',
    mobilePhone: 'ජංගම දුරකථනය',
    email: 'විද්‍යුත් තැපෑල',
    district: 'දිස්ත්‍රික්කය',
    password: 'මුරපදය',
    registerProceed: 'ලියාපදිංචි වී ගෙවීමට යන්න',
    jitsiRoom: 'Jitsi Meet සජීවී කාමරය',
    exitRoom: 'කාමරයෙන් පිටවන්න',
    activeConsultationRoom: 'සක්‍රීය උපදේශන කාමරය',
    consultation: 'උපදේශනය',
    telehealthLink: 'Tele-health සැසි සබැඳිය (Jitsi Meet)',
    closeSessionSubmit: 'සැසිය අවසන් කර සායනික වාර්තාව යවන්න',
    fileIncident: 'සිදුවීමක් වාර්තා කරන්න',
    complaintReviewText: 'ඔබගේ පැමිණිල්ල PsyNova අනුකූලතා නිලධාරීන් විසින් සමාලෝචනය කෙරේ.',
    complaintSuccess: 'පැමිණිල්ල සාර්ථකව යවන ලදී! තහවුරු කිරීම SMS ලොග්වල බලන්න.',
    bookingAssociated: 'අදාළ වෙන්කිරීම',
    appointmentWith: 'වෙන්කිරීම',
    provideDetails: 'විස්තර පැහැදිලිව මෙහි ලියන්න...',
    submitTicket: 'අනුකූලතා කාර්යාලයට ටිකට් යවන්න',
    accountType: 'ගිණුම් වර්ගය',
    clientLoginHint: 'ජංගම දුරකථන අංකය සහ මුරපදය භාවිතා කර ඇතුල් වන්න',
    invalidLogin: 'ජංගම අංකය/මුරපදය වැරදියි හෝ ගිණුම අත්හිටුවා ඇත.',
    mobileNumber: 'ජංගම අංකය',
    timeLeft: 'ඉතිරි කාලය',
    profileNotFound: 'පැතිකඩ හමු නොවීය',
    backToSearch: 'සෙවීමට ආපසු',
    backToSpecialists: 'විශේෂඥවරුන් වෙත ආපසු',
    paymentExpired: 'ගෙවීම් කාලය අවසන් විය. වෙන්කිරීම් වේලාව නැවත නිදහස් කරන ලදී.',
    switchToClient: 'වෙන්කිරීමක් කිරීමට කරුණාකර Client භූමිකාවට මාරු වන්න!',
    slotPublished: 'වේලාව සාර්ථකව පළ කරන ලදී!',
    doctorRegistrationSubmitted: 'ලියාපදිංචිය යවන ලදී! PsyNova admins විසින් SLMC සත්‍යාපනය සිදු කෙරේ.',
  },
  ta: {
    findDoctors: 'மருத்துவரைக் கண்டுபிடி',
    welcomeToPsyNova: 'PsyNova-க்கு வரவேற்கிறோம்',
    heroHeadlinePrefix: 'ஆரோக்கியமான',
    heroHeadlineHighlight: 'மனம்',
    heroHeadlineSuffix: 'செழிப்பான வாழ்வின் அடித்தளம்',
    highStress: 'அதிக மன அழுத்தம்',
    calmingShoreline: 'அமைதியான கரை',
    shorelineMeta: 'இலங்கை அமைதியான கரை உருவகம்',
    shorelineResult: 'பதட்டத்தை அமைதியாக மாற்றுதல்',
    getStarted: 'தொடங்குங்கள்',
    watchIntro: 'அறிமுகத்தைப் பாருங்கள்',
    founderTitle: 'முதன்மை மனநல மருத்துவர் / நிறுவனர்',
    happySouls: '1000+ மகிழ்ச்சியான பயனர்கள்',
    activePatientBase: 'செயலில் உள்ள நோயாளிகள்',
    yearsExperience: 'ஆண்டுகள் அனுபவம்',
    activeMembers: 'செயலில் உள்ள உறுப்பினர்கள்',
    satisfiedClient: 'திருப்தி அடைந்த பயனர்கள்',
    trustedPatients: 'இலங்கை முழுவதும் 100,245+ PsyNova பயனர்களின் நம்பிக்கை',
    aboutUs: 'எங்களைப் பற்றி',
    ourVision: 'எங்கள் நோக்கு',
    ourVisionText: 'இலங்கையின் ஒவ்வொரு வீட்டிற்கும் நவீன மனநல சேவையை எளிதில் கொண்டு செல்லுதல்.',
    ourMission: 'எங்கள் பணி',
    ourMissionText: 'உறுதிப்படுத்தப்பட்ட, பாதுகாப்பான, கருணையுள்ள ஆன்லைன் சுகாதார சேவையை விரைவாக வழங்குதல்.',
    qualityCarePrefix: 'தரமான பராமரிப்பு',
    qualityCareHighlight: 'நிபுணர்களிடமிருந்து',
    aboutPreviewText: 'PsyNova மூலம் இலங்கையின் உரிமம் பெற்ற மனநல மருத்துவர்களுடன் ஆன்லைனில் தொடர்பு கொள்ளலாம். மருத்துவமனைச் செலவு மற்றும் பயண சிரமம் இல்லாமல் பாதுகாப்பான ஆலோசனைகளை வழங்குகிறோம்.',
    learnMore: 'மேலும் அறிக',
    whyChooseUs: 'ஏன் எங்களைத் தேர்வு செய்வது',
    gettingYouPrefix: 'உங்களை மீண்டும்',
    gettingYouHighlight: 'நலத்திற்கு',
    gettingYouSuffix: 'கொண்டு செல்லுதல்',
    whyChooseText: 'உங்கள் நேரம், மொழி மற்றும் தனியுரிமைத் தேவைகளுக்கு ஏற்ப கருணையுள்ள மருத்துவ ஆலோசனைகள்.',
    personalizedCare: 'தனிப்பட்ட பராமரிப்பு',
    personalizedCareText: 'நிபுணர் மருத்துவர்களால் தயாரிக்கப்படும் அறிக்கைகள், மருந்து வழிகாட்டல்கள் மற்றும் மருத்துவ மதிப்பீடுகள்.',
    sandboxTools: 'இலவச சோதனை கருவிகள்',
    sandboxToolsText: 'கட்டண சோதனை, SMS பதிவுகள் மற்றும் வீடியோ அறைகள் ஆகியவற்றை சோதிக்கலாம்.',
    goodService: '24/7 நல்ல சேவை',
    goodServiceText: 'முன்பதிவு, பணம் திரும்புதல் மற்றும் பாதுகாப்பு கேள்விகளுக்கு உள்ளூர் ஆதரவு குழு.',
    searchSub: 'நேரடி ஆலோசனைகளைத் தேடி உறுதிப்படுத்த கீழே பயன்படுத்தவும்',
    filtersClear: 'வடிகட்டிகளை நீக்கு',
    noSlots: 'செயலில் உள்ள நேரங்கள் இல்லை.',
    noDoctors: 'உங்கள் தேடல் வடிகட்டிகளுக்கு பொருந்தும் மருத்துவர்கள் இல்லை.',
    slmcOk: 'SLMC அங்கீகாரம்',
    slmcPendingShort: 'SLMC நிலுவை',
    footerAbout: 'SLMC பதிவு பெற்ற மனநல மருத்துவர்களுடன் பயனர்களை இணைக்கும் 100% ஆன்லைன், பாதுகாப்பான, பலமொழி தளம்.',
    quickNav: 'விரைவு இணைப்புகள்',
    legal: 'சட்டம்',
    pdpaCompliance: 'PDPA இணக்கம்',
    pdpaText: 'இலங்கை தனிப்பட்ட தரவு பாதுகாப்புச் சட்டத்திற்கு இணங்குகிறது. மருத்துவ பதிவுகள் பதிவு செய்யப்படமாட்டாது.',
    footerCopyright: '© 2026 PsyNova. இலங்கை tele-psychiatry தரநிலைக்காக உருவாக்கப்பட்டது.',
    cancel: 'ரத்து செய்',
    close: 'மூடு',
    specialist: 'நிபுணர்',
    dateAndTime: 'தேதி மற்றும் நேரம்',
    doctorFee: 'மருத்துவர் ஆலோசனைக் கட்டணம்',
    platformCommission: 'தள சேவை கட்டணம்',
    cardNumber: 'கார்டு எண்',
    cardHint: 'வெற்றிக்காக 12 இலக்கங்களை உள்ளிடவும்',
    expiryDate: 'காலாவதி தேதி',
    cvv: 'CVV',
    lankaPayRouting: 'LankaPay வழிமாற்று',
    lankaPayText: 'உங்கள் கட்டண கோரிக்கை LankaPay தேசிய அமைப்பின் மூலம் பாதுகாப்பாக அனுப்பப்படும்.',
    authorizing: 'பாதுகாப்பான வலையமைப்பில் கட்டணம் உறுதிப்படுத்தப்படுகிறது...',
    payhereGateway: 'PayHere தளம்',
    patientRegistration: 'நோயாளர் பதிவு',
    patientRegistrationTitle: 'நோயாளர் கணக்கை உருவாக்கவும்',
    patientRegistrationSub: 'மனநல ஆலோசனையை முன்பதிவு செய்ய உங்கள் அடையாளத்தை உறுதிப்படுத்த வேண்டும்.',
    quickSandboxAccess: 'விரைவு சோதனை கணக்கு',
    quickSandboxText: 'படிவங்களைத் தவிர்த்து Kavindu கணக்கில் உடனே உள்நுழையும்.',
    useKavindu: 'Kavindu பயன்படுத்தவும்',
    fullName: 'முழுப் பெயர்',
    nicPassport: 'NIC / பாஸ்போர்ட் எண்',
    mobilePhone: 'கைபேசி',
    email: 'மின்னஞ்சல்',
    district: 'மாவட்டம்',
    password: 'கடவுச்சொல்',
    registerProceed: 'பதிவு செய்து கட்டணத்திற்கு செல்லவும்',
    jitsiRoom: 'Jitsi Meet நேரடி அறை',
    exitRoom: 'அறையிலிருந்து வெளியேறு',
    activeConsultationRoom: 'செயலில் உள்ள ஆலோசனை அறை',
    consultation: 'ஆலோசனை',
    telehealthLink: 'Tele-health ஆலோசனை இணைப்பு (Jitsi Meet)',
    closeSessionSubmit: 'ஆலோசனையை முடித்து மருத்துவ பதிவை சமர்ப்பி',
    fileIncident: 'சம்பவத்தை பதிவு செய்',
    complaintReviewText: 'உங்கள் புகார் PsyNova இணக்க அதிகாரிகளால் பரிசீலிக்கப்படும்.',
    complaintSuccess: 'புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது! உறுதிப்படுத்தலை SMS பதிவுகளில் பாருங்கள்.',
    bookingAssociated: 'சம்பந்தப்பட்ட முன்பதிவு',
    appointmentWith: 'முன்பதிவு',
    provideDetails: 'விவரங்களை தெளிவாக இங்கே எழுதவும்...',
    submitTicket: 'இணக்க அலுவலகத்திற்கு டிக்கெட் அனுப்பு',
    accountType: 'கணக்கு வகை',
    clientLoginHint: 'கைபேசி எண் மற்றும் கடவுச்சொல் மூலம் உள்நுழைவு',
    invalidLogin: 'கைபேசி எண்/கடவுச்சொல் தவறு அல்லது கணக்கு இடைநிறுத்தப்பட்டுள்ளது.',
    mobileNumber: 'கைபேசி எண்',
    timeLeft: 'மீதமுள்ள நேரம்',
    profileNotFound: 'சுயவிவரம் கிடைக்கவில்லை',
    backToSearch: 'தேடலுக்கு திரும்பு',
    backToSpecialists: 'நிபுணர்களுக்கு திரும்பு',
    paymentExpired: 'கட்டண நேரம் முடிந்தது. முன்பதிவு நேரம் மீண்டும் விடுவிக்கப்பட்டது.',
    switchToClient: 'முன்பதிவு செய்ய Client பங்கிற்கு மாற்றவும்!',
    slotPublished: 'நேரம் வெற்றிகரமாக வெளியிடப்பட்டது!',
    doctorRegistrationSubmitted: 'பதிவு சமர்ப்பிக்கப்பட்டது! PsyNova admins SLMC சரிபார்ப்பை நடத்துவார்கள்.',
  },
};
